* minor: more pronounced script error messages

diff --git a/host/tarball/share/myx.common/bin/lib/installEnsurePackage b/host/tarball/share/myx.common/bin/lib/installEnsurePackage
--- a/host/tarball/share/myx.common/bin/lib/installEnsurePackage
+++ b/host/tarball/share/myx.common/bin/lib/installEnsurePackage
@@ -16,7 +16,7 @@ InstallEnsurePackage(){
 	UserRequireRoot "InstallEnsurePackage"
 
 	local NAME="$1"
-	[ -z "$NAME" ] && echo "The utility name is required!" && return 1
+	[ -z "$NAME" ] && echo "ERROR: The utility name is required!" >&2 && return 1
 
 	local LIST=""
 
diff --git a/host/tarball/share/myx.common/bin/lib/installUserGroupMembership b/host/tarball/share/myx.common/bin/lib/installUserGroupMembership
--- a/host/tarball/share/myx.common/bin/lib/installUserGroupMembership
+++ b/host/tarball/share/myx.common/bin/lib/installUserGroupMembership
@@ -11,9 +11,9 @@ InstallUserGroupMembership(){
 	local NAME="$1"; shift;
 	local GRPS="$@"
 
-	test ! -z "$NAME" || ( echo "InstallUserGroupMembership: username is required!" ; exit 1 )
+	test ! -z "$NAME" || ( echo "ERROR: InstallUserGroupMembership: username is required!" >&2 ; exit 1 )
 	if test -z "$GRPS" ; then
-		echo "InstallUserGroupMembership: groupname is taken from username ($NAME)!"
+		echo "WARNING: InstallUserGroupMembership: groupname is taken from username ($NAME)!" >&2
 		local GRPS="$NAME"
 	fi
 	
diff --git a/host/tarball/share/myx.common/bin/vm/list b/host/tarball/share/myx.common/bin/vm/list
--- a/host/tarball/share/myx.common/bin/vm/list
+++ b/host/tarball/share/myx.common/bin/vm/list
@@ -4,7 +4,7 @@
 
 VmList(){
 	if [ -z "`which virsh`" ] ; then
-		echo "VmList: 'virsh' (kvm control utility) is not installed!"
+		echo "ERROR: VmList: 'virsh' (kvm control utility) is not installed!" >&2
 		return 1
 	fi
 	virsh list --all
