* minor: ' [ ! -z ' -> ' [ -n '

diff --git a/host/tarball/share/myx.common/bin/install/updates b/host/tarball/share/myx.common/bin/install/updates
--- a/host/tarball/share/myx.common/bin/install/updates
+++ b/host/tarball/share/myx.common/bin/install/updates
@@ -7,9 +7,9 @@
 
 TryFetchStdout(){
 	local URL="$1"
-	[ ! -z "$URL" ] || (echo "TryFetchStdout: The URL is required!" ; return 0)
-	if [ ! -z "`which curl || true`" ]  ; then curl --silent -L "$URL"  ; return 0 ; fi
-	if [ ! -z "`which wget || true`" ]  ; then wget --quiet -O - "$URL" ; return 0 ; fi
+	[ -n "$URL" ] || (echo "TryFetchStdout: The URL is required!" ; return 0)
+	if [ -n "`which curl || true`" ]  ; then curl --silent -L "$URL"  ; return 0 ; fi
+	if [ -n "`which wget || true`" ]  ; then wget --quiet -O - "$URL" ; return 0 ; fi
 }
 
 InstallUpdates(){
@@ -17,7 +17,7 @@ InstallUpdates(){
 	#   UserRequireRoot
 	# we do:
 	[ `id -u` = 0 ] || { echo "⛔ ERROR: $0: Must be run under root user!" >&2 ; exit 1 ; }
-	[ ! -z "`which apt-get || true`" ] || { echo "⛔ ERROR: $0: apt-get is required!" >&2 ; exit 1 ; }
+	[ -n "`which apt-get || true`" ] || { echo "⛔ ERROR: $0: apt-get is required!" >&2 ; exit 1 ; }
 	
 	TryFetchStdout https://raw.githubusercontent.com/myx/os-myx.common/master/sh-scripts/install-myx.common.sh | sh -e
 	 
@@ -28,7 +28,7 @@ InstallUpdates(){
 	DEBIAN_FRONTEND=noninteractive apt-get dist-upgrade -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold"
 	# apt-get autoremove -y
 	
-	if [ ! -z "`which grub-install || true`" ] ; then
+	if [ -n "`which grub-install || true`" ] ; then
 		echo "'grub-install' present, updating grub config..."
 		update-grub2
 		echo "'grub-install' present, checking disks..."
diff --git a/host/tarball/share/myx.common/bin/lib/installUserGroupMembership b/host/tarball/share/myx.common/bin/lib/installUserGroupMembership
--- a/host/tarball/share/myx.common/bin/lib/installUserGroupMembership
+++ b/host/tarball/share/myx.common/bin/lib/installUserGroupMembership
@@ -11,7 +11,7 @@ InstallUserGroupMembership(){
 	local NAME="$1"; shift;
 	local GRPS="$@"
 
-	test ! -z "$NAME" || ( echo "⛔ ERROR: InstallUserGroupMembership: username is required!" >&2 ; exit 1 )
+	test -n "$NAME" || ( echo "⛔ ERROR: InstallUserGroupMembership: username is required!" >&2 ; exit 1 )
 	if test -z "$GRPS" ; then
 		echo "🙋 WARNING: InstallUserGroupMembership: groupname is taken from username ($NAME)!" >&2
 		local GRPS="$NAME"
