* minor: which -> command -v

diff --git a/host/tarball/share/myx.common/bin/install/updates b/host/tarball/share/myx.common/bin/install/updates
--- a/host/tarball/share/myx.common/bin/install/updates
+++ b/host/tarball/share/myx.common/bin/install/updates
@@ -8,8 +8,10 @@
 TryFetchStdout(){
 	local URL="$1"
 	[ -n "$URL" ] || (echo "TryFetchStdout: The URL is required!" ; return 0)
-	if [ -n "`which curl || true`" ]  ; then curl --silent -L "$URL"  ; return 0 ; fi
-	if [ -n "`which wget || true`" ]  ; then wget --quiet -O - "$URL" ; return 0 ; fi
+    if command -v curl  >/dev/null 2>&1; then curl --silent -L "$URL"; return 0; fi
+    if command -v wget  >/dev/null 2>&1; then wget --quiet -O - "$URL"; return 0; fi
+	echo "⛔ ERROR: curl, fetch, or wget were not found, do not know how to download!" >&2
+    exit 1
 }
 
 InstallUpdates(){
@@ -17,7 +19,7 @@ InstallUpdates(){
 	#   UserRequireRoot
 	# we do:
 	[ `id -u` = 0 ] || { echo "⛔ ERROR: $0: Must be run under root user!" >&2 ; exit 1 ; }
-	[ -n "`which apt-get || true`" ] || { echo "⛔ ERROR: $0: apt-get is required!" >&2 ; exit 1 ; }
+	command -v apt-get >/dev/null 2>&1 || { echo "⛔ ERROR: $0: apt-get is required!" >&2 ; exit 1 ; }
 	
 	TryFetchStdout https://raw.githubusercontent.com/myx/os-myx.common/master/sh-scripts/install-myx.common.sh | sh -e
 	 
