* actual user home to add authorized keys

diff --git a/host/tarball/share/myx.common/bin/os/getUserHome b/host/tarball/share/myx.common/bin/os/getUserHome
--- a/host/tarball/share/myx.common/bin/os/getUserHome
+++ b/host/tarball/share/myx.common/bin/os/getUserHome
@@ -2,7 +2,7 @@
 
 ##### !!! THIS SCRIPT MUST BE OVERRIDEN IN OS-DEPENDENT IMPLEMENTATION !!! #####
 
-OsGetBaseHomeDirectory(){
+OsGetUserHome(){
 	[ -z "$1" ] && \
 		echo "/home" && \
 		return 0
@@ -10,31 +10,31 @@ OsGetBaseHomeDirectory(){
 	set -e
 	if [ "$1" = "--user" ] ; then
 		[ -z "$2" ] && \
-			echo "OsGetBaseHomeDirectory: username required after --user " >&2 && \
+			echo "OsGetUserHome: username required after --user " >&2 && \
 			return 1
 			
 		local HOME_PATH="`grep "^$2\\:" /etc/passwd | cut -d":" -f6`"
 		 
 		[ -z "$HOME_PATH" ] && \
-			echo "OsGetBaseHomeDirectory: no such user: $2" >&2 && \
+			echo "OsGetUserHome: no such user: $2" >&2 && \
 			return 1
 			
 		echo "$HOME_PATH"
 		return 0
 	fi
 	
-	echo "OsGetBaseHomeDirectory: Invalid arguments: $@" >&2
+	echo "OsGetUserHome: Invalid arguments: $@" >&2
 }
 
 
 case "$0" in
-	*/myx.common/bin/os/getBaseHomeDirectory) 
+	*/myx.common/bin/os/getUserHome) 
 		if [ "$1" = "--help" ] ; then
-			echo "Syntax: myx.common os/getBaseHomeDirectory [--user username]" >&2
+			echo "Syntax: myx.common os/getUserHome [--user username]" >&2
 			exit 1
 		fi
 		[ -z "$1" ] && echo "/home" && exit 0;
 		set -e
-		OsGetBaseHomeDirectory "$@"
+		OsGetUserHome "$@"
 	;;
 esac
