* icons in errors

diff --git a/host/tarball/share/myx.common/bin/os/getUserHome b/host/tarball/share/myx.common/bin/os/getUserHome
--- a/host/tarball/share/myx.common/bin/os/getUserHome
+++ b/host/tarball/share/myx.common/bin/os/getUserHome
@@ -10,13 +10,13 @@ OsGetUserHome(){
 	set -e
 	if [ "$1" = "--user" ] ; then
 		[ -z "$2" ] && \
-			echo "ERROR: OsGetUserHome: username required after --user " >&2 && \
+			echo "⛔ ERROR: OsGetUserHome: username required after --user " >&2 && \
 			return 1
 			
 		local HOME_PATH="`grep "^$2\\:" /etc/passwd | cut -d":" -f6`"
 		 
 		[ -z "$HOME_PATH" ] && \
-			echo "ERROR: OsGetUserHome: no such user: $2" >&2 && \
+			echo "⛔ ERROR: OsGetUserHome: no such user: $2" >&2 && \
 			return 1
 			
 		echo "$HOME_PATH"
diff --git a/host/tarball/share/myx.common/bin/vm/list b/host/tarball/share/myx.common/bin/vm/list
--- a/host/tarball/share/myx.common/bin/vm/list
+++ b/host/tarball/share/myx.common/bin/vm/list
@@ -4,7 +4,7 @@
 
 VmList(){
 	if [ -z "`which virsh`" ] ; then
-		echo "ERROR: VmList: 'virsh' (kvm control utility) is not installed!" >&2
+		echo "⛔ ERROR: VmList: 'virsh' (kvm control utility) is not installed!" >&2
 		return 1
 	fi
 	virsh list --all --title
